do.debug:
	Rscript main.r debug && echo [DONE]
do.epsilon:
	Rscript main.r epsilon && echo [DONE]
do.mixing:
	Rscript main.r mixing && echo [DONE]
do.mobility:
	Rscript main.r mobility && echo [DONE]
