do.debug:
	Rscript main.r debug && echo [DONE]
do.contacts:
	Rscript main.r contacts && echo [DONE]
do.mixing:
	Rscript main.r mixing && echo [DONE]
do.mobility:
	Rscript main.r mobility && echo [DONE]
