do.debug:
	Rscript main.r debug && echo [DONE]
do.assumptions:
	Rscript main.r assumptions && echo [DONE]
do.mixing:
	Rscript main.r mixing && echo [DONE]
do.mobility:
	Rscript main.r mobility && echo [DONE]
